### ISSUE TITLE
Delete a wallet

### ISSUE THREAD

**Issue by aksoftware98** [aksoftware98/ak-expenses-tracker#3]
The user must be able to delete an existing wallet.

To delete a wallet a check must be done to make sure that the wallet doesn't have any transactions, otherwise, the transactions must be removed before removing the wallets

## Tasks to be done 
- [ ] Implement the delete functionality in the wallets repository
- [ ] Implement a logical check to make sure that the wallet doesn't have any transactions 
- [ ] Delete all the transactions within a wallet before deleting the wallet
- [ ] Write an Azure Functions with HTTP trigger to delete a wallet by its Id

**Comment by ID-JA** [comment]
Hello @aksoftware98 
What do you think if you implement DeleteRange functionality in  wallets repository so that users can delete multiple wallets at once?

**Comment by aksoftware98** [comment]
Hi @ID-JA 

Thank you so much for the excellent suggestion, I think this feature won't be a good fit for wallets, as every user will have a maximum of 10 wallets, and each one could contain one or one million transactions so basically, we should make the delete process harder not easier to avoid any mistakes that could lead to losing tons of data inserted by the user.
So users should click delete for each wallet and will be asked to review the wallet data before submitting the process.
But I will take this into consideration when implementing delete transactions. 

Thanks!

**Comment by ID-JA** [comment]
That makes sense, I had not considered that.
